name: CI

on:
  push:
  pull_request:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List files
      run: ls -R
